name: attest in various ways

on:
  push:


permissions:
  id-token: write
  attestations: write
  contents: read

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Attest Build Provenance
        uses: actions/attest@v1
        with:
          subject-path: hello.txt
          predicate-type: "<script>alert(\"lol\");</script>"
          predicate: '{}'
